version: "3"

services:

        # Install redis server
        redis-server:
                image: 'redis'
                container_name: movie-cache

        # Backend server setup
        server:
                build: ./backend
                expose:
                        - ${REACT_APP_SERVER_PORT}
                environment:
                        API_HOST: ${API_HOST}
                        REACT_APP_SERVER_PORT: ${REACT_APP_SERVER_PORT}
                ports:
                        - ${REACT_APP_SERVER_PORT}:${REACT_APP_SERVER_PORT}
                env_file:
                        - .env
                volumes:
                        - ./backend/src:/srv/app/movie-search-server/src
                links:
                        - redis-server

        # Client application setup
        client:
                build: ./client
                expose:
                        - ${REACT_APP_PORT}
                environment:
                        REACT_APP_PORT: ${REACT_APP_PORT}
                ports:
                        - ${REACT_APP_PORT}:${REACT_APP_PORT}
                env_file:
                        - .env
                volumes:
                        - ./client/src:/srv/app/movie-search-client/src
                        - ./client/public:/srv/app/movie-search-client/public
                links:
                        - server